services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      redis:
        condition: service_healthy
      maildev:
        condition: service_started

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:80"
  #   restart: unless-stopped
  #   environment:
  #     VITE_API_URL: ${VITE_API_URL}
  #   depends_on:
  #     - backend
